import enum


class Parameter(enum.StrEnum):
    TEST = "TEST"
    ONLINE = "ONLINE"
    MACHINE_TYPE = "MACHINE_TYPE"

    CROP_FILL_RATE = "CROP_FILL_RATE"
    WEIGHT_FRONT = "WEIGHT_FRONT"
    WEIGHT_REAR = "WEIGHT_REAR"
    PTO_SPEED = "PTO_SPEED"

    PIVOT_ANGLE = "PIVOT_ANGLE"
    PIVOT_ANGLE_MAX = "PIVOT_ANGLE_MAX"
    PIVOT_ANGLE_MIN = "PIVOT_ANGLE_MIN"
    PIVOT_SPEED_REFERENCE = "PIVOT_SPEED_REFERENCE"
    PIVOT_UP_PWM = "PIVOT_UP_PWM"
    PIVOT_DOWN_PWM = "PIVOT_DOWN_PWM"

    FOLD_ANGLE = "FOLD_ANGLE"
    FOLD_ANGLE_MAX = "FOLD_ANGLE_MAX"
    FOLD_ANGLE_MIN = "FOLD_ANGLE_MIN"
    FOLD_SPEED_REFERENCE = "FOLD_SPEED_REFERENCE"
    FOLD_OUT_PWM = "FOLD_OUT_PWM"
    FOLD_IN_PWM = "FOLD_IN_PWM"

    TILT_ANGLE = "TILT_ANGLE"
    TILT_ANGLE_MAX = "TILT_ANGLE_MAX"
    TILT_ANGLE_MIN = "TILT_ANGLE_MIN"
    TILT_SPEED_REFERENCE = "TILT_SPEED_REFERENCE"
    TILT_UP_PWM = "TILT_UP_PWM"
    TILT_DOWN_PWM = "TILT_DOWN_PWM"

    ROTATE_ANGLE = "ROTATE_ANGLE"
    ROTATE_ANGLE_MAX = "ROTATE_ANGLE_MAX"
    ROTATE_ANGLE_MIN = "ROTATE_ANGLE_MIN"
    ROTATE_SPEED_REFERENCE = "ROTATE_SPEED_REFERENCE"
    ROTATE_CW_PWM = "ROTATE_CW_PWM"
    ROTATE_CCW_PWM = "ROTATE_CCW_PWM"

    GATE_ANGLE = "GATE_ANGLE"
    GATE_ANGLE_MAX = "GATE_ANGLE_MAX"
    GATE_ANGLE_MIN = "GATE_ANGLE_MIN"
    GATE_SPEED_REFERENCE = "GATE_SPEED_REFERENCE"
    GATE_OPEN_PWM = "GATE_OPEN_PWM"
    GATE_CLOSE_PWM = "GATE_CLOSE_PWM"

    @property
    def name(self):
        return self.value
